spring:
  application:
    name: microservice-student
  config:
    import: optional:configserver:http://localhost:8888


  datasource:
    url: jdbc:mysql://localhost:3307/
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database: mysql

server:
  port: ${PORT:0}  # 0 means random port



eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    enabled: true
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost

logging:
  level:
    sql: debug


management:
  endpoints:
    web:
      exposure:
        include: "*"
