spring:
  application:
    name: microservice-course


  datasource:
    url: jdbc:postgresql://localhost:5433/
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database: postgresql


  config:
    import: optional:configserver:http://localhost:8888

server:
    port: ${PORT:0}


# The following snippet is the same for both microservices
# The only difference is the application name
# The application name is used to register the microservice with Eureka
# The application name is also used to fetch the configuration from the Config Server
eureka:
    client:
        serviceUrl:
          defaultZone: https://${eureka.instance.hostname}:8761/eureka/
    instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      hostname: localhost

