server:
  port: 8761

spring:
  application:
    name: microservice-eureka

eureka:
  instance:
    hostname: localhost # Eureka server hostname
  client:
    registerWithEureka: false # Don't register itself in Eureka
    fetchRegistry: false # Don't fetch registry from Eureka
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/