spring:
    application:
        name: microservice-gateway
    config:
      import: optional:configserver:http://localhost:8888

    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        mvc:
          routes:
            - id: microservice-course # id is a unique identifier for the route
              uri: lb://microservice-course # uri is the target service
              predicates:
                - Path=/api/courses/**

            - id: microservice-student
              uri: lb://microservice-student
              predicates:
                - Path=/api/students/**

